#!/usr/bin/env node
// scripts/codegen.mjs — Deterministic asset codegen for ReScript cutover WU-1.
// Reads canonical JSON, emits git-ignored .res modules.
// Exit codes: 0 success, 1 drift/self-check failure, 2 I/O error.
//
// Usage:
//   node scripts/codegen.mjs          — write generated files
//   node scripts/codegen.mjs --check  — verify drift (exit 0 = clean, 1 = drift)

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// ── Paths ──────────────────────────────────────────────────────────────────────

/** Project root — resolved from this script's location */
const PROJECT_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const CANONICAL_SCHEMA = join(PROJECT_ROOT, "schemas", "quotas.schema.json");
const CANONICAL_CATALOG = join(PROJECT_ROOT, "src", "i18n", "locales", "en.json");

// Output paths use subdirectories so the module name (ConfigLoader.Schema) doesn't
// conflict with the consumer module name (ConfigLoader) at the same namespace level.
// In ReScript, file "src/Infra/ConfigLoader/Schema.res" compiles to module
// "ConfigLoader.Schema", which IS accessible from src/Infra/ConfigLoader.res.
const OUTPUT_SCHEMA = join(PROJECT_ROOT, "src", "Infra", "ConfigLoader", "Schema.res");
const OUTPUT_CATALOG = join(PROJECT_ROOT, "src", "i18n", "Translator", "EnCatalog.res");

// ── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Recursively sort all object keys in a JSON value, producing canonical form.
 * Arrays retain original order; strings/numbers/null are returned as-is.
 */
function sortKeys(value) {
  if (Array.isArray(value)) {
    return value.map(sortKeys);
  }
  if (value !== null && typeof value === "object") {
    return Object.keys(value)
      .sort()
      .reduce((acc, key) => {
        acc[key] = sortKeys(value[key]);
        return acc;
      }, {});
  }
  return value;
}

/**
 * Escape a JSON string for embedding inside a JS/ReScript template literal.
 *
 * CRITICAL: Do NOT escape backslashes here.
 * JSON.stringify already escapes backslashes as `\\`. In a JS template literal,
 * `\\` evaluates to a single `\`, which is exactly what JSON.parse expects.
 * Re-escaping `\\` → `\\\\` would double-backslash after template evaluation.
 *
 * Only escape characters that have special meaning in template literals:
 * - backticks: end the template literal
 * - ${ : begins template interpolation
 */
function escapeForTemplateLiteral(jsonString) {
  return jsonString
    .replace(/`/g, "\\`")          // escape backticks
    .replace(/\$\{/g, "\\${");     // escape ${ to prevent interpolation
}

/**
 * Undo the escape sequences we added for template literals.
 * Only reverses: \` → `, \${ → ${
 */
function unescapeTemplateLiteral(escaped) {
  return escaped
    .replace(/\\`/g, "`")
    .replace(/\\\$\{/g, "${");
}

// ── Schema emitter ─────────────────────────────────────────────────────────────

function emitSchema(canonicalJson) {
  const canonical = JSON.parse(canonicalJson);
  const sorted = sortKeys(canonical);
  const formatted = JSON.stringify(sorted, null, 2) + "\n";
  const escaped = escapeForTemplateLiteral(formatted);

  // Typed ReScript: JSON.parseOrThrow over a template literal.
  // Output: JSON.parseOrThrow(`{escaped_json}`)
  const header = "// GENERATED by scripts/codegen.mjs — do not edit. Regenerate via: pnpm codegen\n";
  return header + `let schema: JSON.t = JSON.parseOrThrow(\`${escaped}\`)\n`;
}

// ── Catalog emitter ────────────────────────────────────────────────────────────

function emitCatalog(canonicalJson) {
  const catalog = JSON.parse(canonicalJson);
  // Sort keys lexicographically for idempotent output
  const sortedEntries = Object.entries(catalog).sort(([a], [b]) =>
    a < b ? -1 : a > b ? 1 : 0
  );

  const tuples = sortedEntries
    .map(([k, v]) => `  ("${k}", "${v}")`)
    .join(",\n");

  const header = "// GENERATED by scripts/codegen.mjs — do not edit. Regenerate via: pnpm codegen\n";
  return header + `let enCatalog: dict<string> = Dict.fromArray([\n${tuples}\n])\n`;
}

// ── Round-trip self-check ─────────────────────────────────────────────────────

/**
 * Determine if the backtick at position `idx` is escaped (preceded by odd number of backslashes).
 */
function isUnescapedBacktick(s, idx) {
  let count = 0;
  for (let j = idx - 1; j >= 0 && s[j] === "\\"; j--) {
    count++;
  }
  return count % 2 === 0;
}

/**
 * Extract the JSON payload from the generated schema file.
 *
 * The schema is emitted as: JSON.parseOrThrow(`{escaped_json}`)
 * We find the opening backtick (after JSON.parseOrThrow() and the closing backtick (preceded by \n}\n),
 * then extract the content between them.
 */
function extractSchemaPayload(content) {
  // Find JSON.parseOrThrow(`
  const opener = "JSON.parseOrThrow(`";
  const openerIdx = content.indexOf(opener);
  if (openerIdx === -1) throw new Error(`No ${opener} found`);
  const outerBacktickPos = openerIdx + opener.length - 1;
  if (!isUnescapedBacktick(content, outerBacktickPos)) {
    throw new Error("Opening backtick is escaped");
  }

  // Find closing backtick: first unescaped ` preceded by \n}\n
  let innerClosePos = -1;
  for (let i = outerBacktickPos + 1; i < content.length; i++) {
    if (content[i] === "`" && isUnescapedBacktick(content, i)) {
      const prev3 = content.slice(Math.max(0, i - 3), i);
      if (prev3 === "\n}\n") {
        innerClosePos = i;
        break;
      }
    }
  }
  if (innerClosePos === -1) throw new Error("Closing backtick not found");

  // Extract JSON between the backticks
  const rawJson = content.slice(outerBacktickPos + 1, innerClosePos);
  return unescapeTemplateLiteral(rawJson);
}

/**
 * Round-trip check: parse the embedded JSON and compare to canonical.
 * Returns null if equal, or an error message string if drifted.
 */
function checkSchemaDrift(canonicalJson, generatedContent) {
  try {
    const embedded = extractSchemaPayload(generatedContent);
    const embeddedParsed = JSON.parse(embedded);
    const canonicalParsed = JSON.parse(canonicalJson);
    const canonicalSorted = sortKeys(canonicalParsed);
    const embeddedSorted = sortKeys(embeddedParsed);

    if (JSON.stringify(embeddedSorted) !== JSON.stringify(canonicalSorted)) {
      return "Schema drift: embedded JSON does not match canonical";
    }
    return null;
  } catch (err) {
    return `Schema self-check failed: ${err.message}`;
  }
}

/**
 * Round-trip check for catalog: parse Dict.fromArray tuples and compare to canonical.
 */
function checkCatalogDrift(canonicalJson, generatedContent) {
  try {
    const canonical = JSON.parse(canonicalJson);
    const tupleRegex = /\("([^"]+)",\s*"([^"]*)"\)/g;
    const generated = {};
    let m;
    tupleRegex.lastIndex = 0;
    while ((m = tupleRegex.exec(generatedContent)) !== null) {
      generated[m[1]] = m[2];
    }

    const keys = Object.keys(canonical);
    for (const key of keys) {
      if (!(key in generated)) {
        return `Catalog drift: missing key "${key}" in generated catalog`;
      }
      if (generated[key] !== canonical[key]) {
        return `Catalog drift: key "${key}" has value "${generated[key]}" but canonical has "${canonical[key]}"`;
      }
    }
    for (const key of Object.keys(generated)) {
      if (!(key in canonical)) {
        return `Catalog drift: unexpected key "${key}" in generated catalog`;
      }
    }
    return null;
  } catch (err) {
    return `Catalog self-check failed: ${err.message}`;
  }
}

// ── File helpers ─────────────────────────────────────────────────────────────

function readCanonical(path, type) {
  if (!existsSync(path)) {
    console.error(`codegen: canonical ${type} not found: ${path}`);
    process.exit(2);
  }
  try {
    return readFileSync(path, "utf8");
  } catch (err) {
    console.error(`codegen: failed to read canonical ${type} at ${path}: ${err.message}`);
    process.exit(2);
  }
}

function writeGenerated(path, content, type) {
  try {
    const dir = dirname(path);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(path, content, "utf8");
  } catch (err) {
    console.error(`codegen: failed to write ${type} at ${path}: ${err.message}`);
    process.exit(2);
  }
}

function readGenerated(path) {
  if (!existsSync(path)) return null;
  try {
    return readFileSync(path, "utf8");
  } catch {
    return null;
  }
}

// ── Main ─────────────────────────────────────────────────────────────────────

const CHECK_MODE = process.argv.includes("--check");

function main() {
  const canonicalSchema = readCanonical(CANONICAL_SCHEMA, "schema");
  const canonicalCatalog = readCanonical(CANONICAL_CATALOG, "catalog");

  const generatedSchema = emitSchema(canonicalSchema);
  const generatedCatalog = emitCatalog(canonicalCatalog);

  if (CHECK_MODE) {
    let hasDrift = false;

    const existingSchema = readGenerated(OUTPUT_SCHEMA);
    if (existingSchema) {
      const drift = checkSchemaDrift(canonicalSchema, existingSchema);
      if (drift) {
        console.error(`codegen --check: ${drift}`);
        hasDrift = true;
      }
    } else {
      console.error("codegen --check: generated schema file is missing");
      hasDrift = true;
    }

    const existingCatalog = readGenerated(OUTPUT_CATALOG);
    if (existingCatalog) {
      const drift = checkCatalogDrift(canonicalCatalog, existingCatalog);
      if (drift) {
        console.error(`codegen --check: ${drift}`);
        hasDrift = true;
      }
    } else {
      console.error("codegen --check: generated catalog file is missing");
      hasDrift = true;
    }

    if (hasDrift) process.exit(1);
    return;
  }

  // Write mode: only write if content differs
  const existingSchema = readGenerated(OUTPUT_SCHEMA);
  if (!existingSchema || existingSchema !== generatedSchema) {
    writeGenerated(OUTPUT_SCHEMA, generatedSchema, "schema");
    console.log(`codegen: wrote ${OUTPUT_SCHEMA}`);
  } else {
    console.log(`codegen: schema up-to-date (no change)`);
  }

  const existingCatalog = readGenerated(OUTPUT_CATALOG);
  if (!existingCatalog || existingCatalog !== generatedCatalog) {
    writeGenerated(OUTPUT_CATALOG, generatedCatalog, "catalog");
    console.log(`codegen: wrote ${OUTPUT_CATALOG}`);
  } else {
    console.log(`codegen: catalog up-to-date (no change)`);
  }

  // Self-check after write
  const writtenSchema = readGenerated(OUTPUT_SCHEMA);
  const schemaDrift = checkSchemaDrift(canonicalSchema, writtenSchema);
  if (schemaDrift) {
    console.error(`codegen: SELF-CHECK FAILED — ${schemaDrift}`);
    process.exit(1);
  }

  const writtenCatalog = readGenerated(OUTPUT_CATALOG);
  const catalogDrift = checkCatalogDrift(canonicalCatalog, writtenCatalog);
  if (catalogDrift) {
    console.error(`codegen: SELF-CHECK FAILED — ${catalogDrift}`);
    process.exit(1);
  }

  console.log("codegen: all generated files verified");
}

main();
